package io.github.ian_miller.wuziqi.ui.theme

import androidx.compose.runtime.compositionLocalOf

// ─── 所有 UI 文字 ──────────────────────────────────────────────────────────────

data class AppStrings(
    // ── 通用 ──────────────────────────────────────────────────────────────────
    val confirm: String,
    val cancel: String,
    val close: String,
    val save: String,
    val done: String,
    val create: String,
    val skip: String,
    val edit: String,
    val selected: String,

    // ── 难度 ──────────────────────────────────────────────────────────────────
    val easy: String,
    val medium: String,
    val hard: String,
    val master: String,
    val easyMode: String,
    val mediumMode: String,
    val hardMode: String,
    val masterMode: String,

    // ── 主菜单 ────────────────────────────────────────────────────────────────
    val appTitle: String,
    val viewProfileHint: String,
    val tutorialBtn: String,
    val settingsBtn: String,
    val remotePlay: String,
    val vsAi: String,
    val vsHuman: String,
    val resume: String,
    val clickToCreatePlayer: String,

    // ── 游戏 HUD ──────────────────────────────────────────────────────────────
    val blackFirst: String,
    val whiteSecond: String,
    val yourTurn: String,
    val playerTurnFmt: (String) -> String,
    val aiThinking: String,
    val aiThinkingElapsedFmt: (Int) -> String,
    val waitingOpponent: String,
    val victoryStamp: String,
    val drawStamp: String,
    val aiFirstBlack: String,
    val playerFirstBlack: String,
    val xFirstBlack: (String) -> String,
    val xFirstSuffix: String,   // " 先手 (执黑)" / " First (Black)" — used for styled name + suffix layout
    val clickToStart: String,
    val win: String,

    // ── 控制按钮 ──────────────────────────────────────────────────────────────
    val undo: String,
    val stop: String,
    val hint: String,
    val aiGoFirst: String,
    val iGoFirst: String,
    val copyBoard: String,
    val copied: String,

    // ── 状态 Chip ─────────────────────────────────────────────────────────────
    val reconnecting: String,
    val drawChip: String,
    val youWinChip: String,
    val opponentWinsChip: String,
    val myBlackTurn: String,
    val myWhiteTurn: String,
    val opponentBlackTurn: String,
    val opponentWhiteTurn: String,

    // ── 设置对话框 ────────────────────────────────────────────────────────────
    val gameSettings: String,
    val difficultyLabel: String,
    val savedGameWarning: String,
    val sound: String,
    val vibration: String,
    val allowUndo: String,
    val aiAssist: String,
    val magnifier: String,
    val stopGame: String,
    val exitGame: String,
    val language: String,
    val langAuto: String,
    val langEnglish: String,
    val langChinese: String,
    val currentVersionFmt: (String) -> String,

    // ── 玩家档案 ──────────────────────────────────────────────────────────────
    val playerCenter: String,
    val newAccount: String,
    val createNewAccount: String,
    val winRecord: String,
    val switchAccount: String,
    val winRateLabel: String,
    val winLossLabel: String,
    val totalGamesLabel: String,
    val totalGames: String,
    val wins: String,
    val losses: String,
    val renameTitle: String,
    val newNickname: String,
    val nickname: String,
    val noData: String,
    val vsAiLabel: String,
    val vsHumanLabel: String,

    // ── 远程大厅 ──────────────────────────────────────────────────────────────
    val remoteLobbyTitle: String,
    val creatingRoom: String,
    val joiningRoom: String,
    val waitingConnection: String,
    val gameInProgress: String,
    val connectionFailed: String,
    val cancelAction: String,
    val backToMain: String,
    val scanQr: String,
    val gallery: String,
    val joinGame: String,
    val inputInviteCode: String,
    val inputInviteCodeHint: String,
    val inviteCodeLabel: String,
    val pasteInviteCode: String,
    val waitingHost: String,
    val preparing: String,
    val qrScanFailed: String,
    val qrNotFound: String,
    val qrImageLoadFailed: String,
    val qrNotFoundDetail: String,
    val inviteCodeInvalidLan: String,
    val connectionTimeoutMsg: String,
    val networkUnavailableMsg: String,
    val relayUnavailableMsg: String,
    val versionMismatchMsg: String,

    // ── 远程棋盘 ──────────────────────────────────────────────────────────────
    val opponent: String,
    val me: String,
    val requestDraw: String,
    val resign: String,
    val connectionLost: String,
    val returnToLobby: String,
    val confirmResignTitle: String,
    val confirmResignText: String,
    val confirmResign: String,
    val drawOfferedTitle: String,
    val drawOfferedText: String,
    val acceptDraw: String,
    val rejectDraw: String,
    val drawSentWaiting: String,  // 我方求和等待回应
    val exitMatch: String,
    val exitMatchHint: String,
    // ── 再来一局 ──────────────────────────────────────────────────────────────
    val rematchRequest: String,
    val rematchRequestSent: String,
    val rematchOffered: (String) -> String,  // "{对方}请求再来一局，{对方}执{颜色}"
    val rematchAccepted: String,
    val rematchRejected: String,
    val rematchTimeout: String,
    val clickToRematch: String,

    // ── 游戏结束徽章 ──────────────────────────────────────────────────────────
    val resumeBadge: String,

    // ── 教程 ──────────────────────────────────────────────────────────────────
    val tutorialTitle: String,

    // ── 教程内容 ──────────────────────────────────────────────────────────────
    val tutorialIntroTitle: String,
    val tutorialIntro1: String,
    val tutorialIntro2: String,
    val tutorialRulesTitle: String,
    val tutorialRule1: String,
    val tutorialRule2: String,
    val tutorialRule3: String,
    val tutorialRule4: String,
    val tutorialRule5: String,
    val tutorialModesTitle: String,
    val tutorialModeAiTitle: String,
    val tutorialModeAiDesc: String,
    val tutorialModeHumanTitle: String,
    val tutorialModeHumanDesc: String,
    val tutorialFeaturesTitle: String,
    val tutorialMagnifierTitle: String,
    val tutorialMagnifierDesc: String,
    val tutorialAiHintTitle: String,
    val tutorialAiHintDesc: String,
    val tutorialUndoFeatTitle: String,
    val tutorialUndoFeatDesc: String,
    val tutorialStatsFeatTitle: String,
    val tutorialStatsFeatDesc: String,
    val tutorialTipsTitle: String,
    val tutorialBeginnerLevel: String,
    val tutorialBeginnerTips: List<String>,
    val tutorialIntermLevel: String,
    val tutorialIntermTips: List<String>,
    val tutorialAdvancedLevel: String,
    val tutorialAdvancedTips: List<String>,
    val tutorialFooter1: String,
    val tutorialFooter2: String,

    // ── 远程大厅内容 ──────────────────────────────────────────────────────────
    val remoteTagline: String,
    val remoteSubtitle: String,
    val remoteActiveGameTitle: String,
    val remoteResumeGame: String,
    val remoteEndGame: String,
    val remoteCreateHint: String,
    val remoteCheckingRelays: String,
    val remoteRelayDown: String,
    val remoteRelayDownNote: String,
    val remoteCreateOnline: String,
    val remoteRelayStatus: (Int, Int) -> String,
    val remoteLanCreate: String,
    val remoteLanHint: String,
    val remoteJoinAction: String,
    val remoteConnectedTitle: String,
    val remoteGamePaused: String,
    val remoteYouBlack: String,
    val remoteYouWhite: String,
    val remoteAutoReconnect: String,
    val remoteForfeit: String,
    val remoteLanRoomReady: String,
    val remoteShareInvite: String,
    val remoteLanInstructions: String,
    val remoteOnlineInstructions: String,
    val remoteCopied: String,
    val remoteCopyCode: String,
    val remoteSavedGallery: String,
    val remoteSaveFailed: String,
    val remoteSaveImage: String,
    val remoteShareAction: String,
    val remoteWaitingFriend: String,
    val remoteProcessing: String,
    val remoteRetry: String,
    val remoteRelayCount: (Int, Int) -> String,

    // ── 游戏状态栏 ────────────────────────────────────────────────────────────
    val statusSelectFirst: String,           // 未开始：请选择先手方
    val statusAiThinking: String,            // AI 思考中
    val statusBlackTurn: String,             // 双人模式：轮到黑方
    val statusWhiteTurn: String,             // 双人模式：轮到白方
    val statusAiTurnFmt: (String) -> String, // VS AI 模式：轮到 {颜色} (AI)
    val statusPlayerTurnFmt: (String) -> String, // VS AI 模式：轮到 {颜色} (玩家)
    val statusBlackWins: String,             // 黑方获胜
    val statusWhiteWins: String,             // 白方获胜
    val statusDraw: String,                  // 平局
    val statusGameOverBlackWins: String,
    val statusGameOverWhiteWins: String,
    val statusGameOverDraw: String,
    val statusGameOver: String,
    val colorBlack: String,
    val colorWhite: String,
    val playerHudYourTurn: String,
    val playerHudWaitOpponent: String,
    val playerHudWin: String,
    val playerHudLose: String,
    val playerHudDraw: String,
    val playerHudReady: String,
)

// ─── 中文 ──────────────────────────────────────────────────────────────────────

val ZhStrings = AppStrings(
    confirm = "确认",
    cancel = "取消",
    close = "关闭",
    save = "保存",
    done = "完成",
    create = "创建",
    skip = "跳过",
    edit = "编辑",
    selected = "已选",

    easy = "简单",
    medium = "中等",
    hard = "困难",
    master = "大师",
    easyMode = "简单模式",
    mediumMode = "中等模式",
    hardMode = "困难模式",
    masterMode = "大师模式",

    appTitle = "五子棋",
    viewProfileHint = "查看战绩与切换账号",
    tutorialBtn = "游戏说明",
    settingsBtn = "游戏设置",
    remotePlay = "远程对弈",
    vsAi = "人机对战",
    vsHuman = "双人对战",
    resume = "续局",
    clickToCreatePlayer = "点击创建玩家",

    blackFirst = "黑方 (先手)",
    whiteSecond = "白方 (后手)",
    yourTurn = "你的回合",
    playerTurnFmt = { name -> "${name}的回合" },
    aiThinking = "思考中...",
    aiThinkingElapsedFmt = { seconds -> "已思考 ${seconds} 秒" },
    waitingOpponent = "等待对方落子...",
    victoryStamp = "胜 利",
    drawStamp = "平 局",
    aiFirstBlack = "AI先手 (执黑)",
    playerFirstBlack = "我方先手 (执黑)",
    xFirstBlack = { name -> "${name}先手 (执黑)" },
    xFirstSuffix = " 先手 (执黑)",
    clickToStart = "点击开始",
    win = "获胜!",

    undo = "撤销",
    stop = "结束",
    hint = "提示",
    aiGoFirst = "AI先手",
    iGoFirst = "我先手",
    copyBoard = "复制棋盘",
    copied = "已复制",

    reconnecting = "⚠️ 重连中…",
    drawChip = "平局",
    youWinChip = "🎉 你赢了！",
    opponentWinsChip = "对方获胜",
    myBlackTurn = "⚫ 你的回合",
    myWhiteTurn = "⚪ 你的回合",
    opponentBlackTurn = "⚫ 对方回合",
    opponentWhiteTurn = "⚪ 对方回合",

    gameSettings = "游戏设置",
    difficultyLabel = "难度选择",
    savedGameWarning = "⚠ 人机对战模式存在进行中的对局，完成后方可修改难度",
    sound = "音效",
    vibration = "震动",
    allowUndo = "允许撤销",
    aiAssist = "AI 辅助 (仅双人)",
    magnifier = "落子放大镜",
    stopGame = "结束本局",
    exitGame = "退出游戏",
    language = "界面语言",
    langAuto = "跟随系统",
    langEnglish = "English",
    langChinese = "中文",
    currentVersionFmt = { version -> "当前版本: $version" },

    playerCenter = "玩家中心",
    newAccount = "新建",
    createNewAccount = "新建账号",
    winRecord = "战绩统计",
    switchAccount = "切换账号",
    winRateLabel = "胜率",
    winLossLabel = "胜/负",
    totalGamesLabel = "总局",
    totalGames = "总场次",
    wins = "获胜",
    losses = "落败",
    renameTitle = "修改昵称",
    newNickname = "新昵称",
    nickname = "昵称",
    noData = "暂无数据",
    vsAiLabel = "人机模式",
    vsHumanLabel = "双人模式",

    remoteLobbyTitle = "远程对弈",
    creatingRoom = "创建房间",
    joiningRoom = "加入房间",
    waitingConnection = "等待连接",
    gameInProgress = "对局进行中",
    connectionFailed = "连接失败",
    cancelAction = "取消操作",
    backToMain = "返回主菜单",
    scanQr = "扫码",
    gallery = "相册",
    joinGame = "加入对局",
    inputInviteCode = "输入邀请码",
    inputInviteCodeHint = "将好友发送的邀请码粘贴在此处，\n或扫描 QR 码直接加入",
    inviteCodeLabel = "邀请码",
    pasteInviteCode = "粘贴邀请码…",
    waitingHost = "等待房主确认…",
    preparing = "准备中…",
    qrScanFailed = "二维码识别失败，请重试",
    qrNotFound = "未找到有效的二维码",
    qrImageLoadFailed = "图片加载失败，请重新选择",
    qrNotFoundDetail = "请确保照片中包含完整且清晰的二维码",
    inviteCodeInvalidLan = "局域网邀请码格式不正确",
    connectionTimeoutMsg = "连接超时，请确认房主已创建房间且双方在同一网络",
    networkUnavailableMsg = "无法获取本机局域网 IP，请确认已连接 WiFi 或已开启热点",
    relayUnavailableMsg = "中继不可用，无法加入线上房间。请改用局域网模式",
    versionMismatchMsg = "对方使用的版本可能不兼容，建议双方更新到最新版本",

    opponent = "对方",
    me = "我",
    requestDraw = "求和",
    resign = "认输",
    connectionLost = "连接已断开，正在自动重连…",
    returnToLobby = "返回大厅",
    confirmResignTitle = "确认认输？",
    confirmResignText = "认输后对局结束，将清除本地存档。",
    confirmResign = "确认认输",
    drawOfferedTitle = "对方求和",
    drawOfferedText = "对方求和，是否接受？",
    acceptDraw = "接受和棋",
    rejectDraw = "拒绝",
    drawSentWaiting = "等待求和回应…",
    exitMatch = "退出对局",
    exitMatchHint = "复盘后点此退出",
    rematchRequest = "再来一局",
    rematchRequestSent = "等待对方回应…",
    rematchOffered = { color -> "再来一局？对方执$color" },
    rematchAccepted = "对方已接受",
    rematchRejected = "对方已拒绝",
    rematchTimeout = "请求已超时",
    clickToRematch = "点击选择先后手",

    resumeBadge = "续局",

    tutorialTitle = "游戏说明",

    tutorialIntroTitle = "游戏简介",
    tutorialIntro1 = "五子棋是一种两人对弈的纯策略型棋类游戏，起源于中国古代，历史悠久，简单易学却又变化无穷。",
    tutorialIntro2 = "游戏目标是率先在横、竖或斜向连成五子，即可获胜。看似简单，实则蕴含着深厚的策略智慧。",
    tutorialRulesTitle = "基本规则",
    tutorialRule1 = "黑方先行，双方轮流在棋盘交叉点落子",
    tutorialRule2 = "棋子落下后不可移动或移除",
    tutorialRule3 = "先在横、竖、斜任意方向连成五子者获胜",
    tutorialRule4 = "六子及以上不算赢棋，仍算五子连珠",
    tutorialRule5 = "棋盘下满仍无五子连珠则为和棋",
    tutorialModesTitle = "游戏模式",
    tutorialModeAiTitle = "人机对战",
    tutorialModeAiDesc = "与AI对手切磋棋艺。可选择不同难度级别：入门、简单、中等、困难。适合练习和提升自己。",
    tutorialModeHumanTitle = "双人对战",
    tutorialModeHumanDesc = "两位玩家在同一设备上轮流对战。支持翻转棋盘，方便面对面切磋。适合与朋友一起游戏。",
    tutorialFeaturesTitle = "特色功能",
    tutorialMagnifierTitle = "放大镜功能",
    tutorialMagnifierDesc = "落子时会显示放大镜，精确定位落子位置，避免误触。",
    tutorialAiHintTitle = "AI助手",
    tutorialAiHintDesc = "陷入困境？点击AI助手按钮，获得最佳落子建议。",
    tutorialUndoFeatTitle = "悔棋功能",
    tutorialUndoFeatDesc = "不小心点错了？使用悔棋功能撤回上一步。",
    tutorialStatsFeatTitle = "战绩统计",
    tutorialStatsFeatDesc = "自动记录每局对战结果，随时查看胜率统计。",
    tutorialTipsTitle = "游戏技巧",
    tutorialBeginnerLevel = "初级技巧",
    tutorialBeginnerTips = listOf(
        "控制中心：棋盘中心位置价值最高，尽量占据",
        "积极进攻：不要一味防守，主动制造威胁",
        "观察活三：形成活三（两端都开放的连续三子）是制胜关键"
    ),
    tutorialIntermLevel = "进阶技巧",
    tutorialIntermTips = listOf(
        "双活三：同时制造两个活三，对手无法同时防守",
        "冲四活三：一个四子连珠加一个活三，必胜局面",
        "防守反击：堵住对手的同时，也为自己创造机会",
        "预判三步：思考对手可能的应对，提前布局"
    ),
    tutorialAdvancedLevel = "高级战术",
    tutorialAdvancedTips = listOf(
        "开局定式：学习经典开局如花月、浦月等",
        "禁手规则：正式比赛中黑方有三三禁、四四禁、长连禁",
        "形势判断：学会评估当前局面的优劣",
        "弃子争先：有时放弃局部利益，换取整体优势"
    ),
    tutorialFooter1 = "熟能生巧，多练习才能成为高手！",
    tutorialFooter2 = "祝您游戏愉快！",

    remoteTagline = "与好友远程对弈",
    remoteSubtitle = "通过邀请码或 QR 码连接，加密通信",
    remoteActiveGameTitle = "⚔️ 对局进行中",
    remoteResumeGame = "继续对局",
    remoteEndGame = "结束对局",
    remoteCreateHint = "邀请好友加入，你执黑棋先手",
    remoteCheckingRelays = "检测网络中继…",
    remoteRelayDown = "中继不可用，点击重试",
    remoteRelayDownNote = "已记录，下次不会自动连接",
    remoteCreateOnline = "创建房间（网络对弈）",
    remoteRelayStatus = { c, t -> "已连接 $c/$t 中继" },
    remoteLanCreate = "局域网创建",
    remoteLanHint = "同一 WiFi 或热点，无需外网",
    remoteJoinAction = "加入对局（粘贴或扫码邀请码）",
    remoteConnectedTitle = "对局进行中",
    remoteGamePaused = "对局已暂停",
    remoteYouBlack = "你执黑棋（先手）",
    remoteYouWhite = "你执白棋（后手）",
    remoteAutoReconnect = "正在尝试自动重连对方…",
    remoteForfeit = "结束对局（认输）",
    remoteLanRoomReady = "📶 局域网开房准备",
    remoteShareInvite = "将邀请码发给好友",
    remoteLanInstructions = "好友扫码或粘贴邀请码后双方自动开始对局\n需要在同一 WiFi 或热点下",
    remoteOnlineInstructions = "好友扫描 QR 码或粘贴邀请码后\n双方自动开始对局",
    remoteCopied = "已复制！",
    remoteCopyCode = "复制邀请码",
    remoteSavedGallery = "已保存到相册 📷",
    remoteSaveFailed = "保存失败，请检查存储权限",
    remoteSaveImage = "保存图片",
    remoteShareAction = "分享",
    remoteWaitingFriend = "等待好友加入…",
    remoteProcessing = "处理中…",
    remoteRetry = "重试",
    remoteRelayCount = { c, t -> "$c/$t 中继" },

    statusSelectFirst = "请选择先手方",
    statusAiThinking = "AI 思考中...",
    statusBlackTurn = "轮到黑方行动",
    statusWhiteTurn = "轮到白方行动",
    statusAiTurnFmt = { color -> "轮到: $color (AI)" },
    statusPlayerTurnFmt = { color -> "轮到: $color (玩家)" },
    statusBlackWins = "获胜者: 黑方",
    statusWhiteWins = "获胜者: 白方",
    statusDraw = "平局",
    statusGameOverBlackWins = "游戏结束 - 黑方获胜",
    statusGameOverWhiteWins = "游戏结束 - 白方获胜",
    statusGameOverDraw = "游戏结束 - 平局",
    statusGameOver = "游戏结束",
    colorBlack = "黑方",
    colorWhite = "白方",
    playerHudYourTurn = "轮到你落子",
    playerHudWaitOpponent = "等待对手",
    playerHudWin = "胜利! 🎉",
    playerHudLose = "失败",
    playerHudDraw = "平局",
    playerHudReady = "准备中",
)

// ─── English ───────────────────────────────────────────────────────────────────

val EnStrings = AppStrings(
    confirm = "Confirm",
    cancel = "Cancel",
    close = "Close",
    save = "Save",
    done = "Done",
    create = "Create",
    skip = "Skip",
    edit = "Edit",
    selected = "✓",

    easy = "Easy",
    medium = "Med.",
    hard = "Hard",
    master = "Master",
    easyMode = "Easy Mode",
    mediumMode = "Medium Mode",
    hardMode = "Hard Mode",
    masterMode = "Master Mode",

    appTitle = "Gomoku",
    viewProfileHint = "View stats & switch account",
    tutorialBtn = "Tutorial",
    settingsBtn = "Settings",
    remotePlay = "Remote Play",
    vsAi = "vs Computer",
    vsHuman = "2 Players",
    resume = "Resume",
    clickToCreatePlayer = "Tap to create player",

    blackFirst = "Black (First)",
    whiteSecond = "White (Second)",
    yourTurn = "Your Turn",
    playerTurnFmt = { name -> "$name's Turn" },
    aiThinking = "Thinking…",
    aiThinkingElapsedFmt = { seconds -> "Thinking ${seconds}s" },
    waitingOpponent = "Waiting…",
    victoryStamp = "WIN",
    drawStamp = "DRAW",
    aiFirstBlack = "AI First (Black)",
    playerFirstBlack = "I Go First (Black)",
    xFirstBlack = { name -> "$name First (Black)" },
    xFirstSuffix = " First (Black)",
    clickToStart = "Tap to start",
    win = "Win!",

    undo = "Undo",
    stop = "End",
    hint = "Hint",
    aiGoFirst = "AI First",
    iGoFirst = "Me First",
    copyBoard = "Copy Board",
    copied = "Copied",

    reconnecting = "⚠️ Reconnecting…",
    drawChip = "Draw",
    youWinChip = "🎉 You Win!",
    opponentWinsChip = "Opponent Wins",
    myBlackTurn = "⚫ Your Turn",
    myWhiteTurn = "⚪ Your Turn",
    opponentBlackTurn = "⚫ Their Turn",
    opponentWhiteTurn = "⚪ Their Turn",

    gameSettings = "Settings",
    difficultyLabel = "Difficulty",
    savedGameWarning = "⚠ A game is in progress. Finish it before changing difficulty.",
    sound = "Sound",
    vibration = "Vibration",
    allowUndo = "Allow Undo",
    aiAssist = "AI Hint (2P only)",
    magnifier = "Magnifier",
    stopGame = "End Game",
    exitGame = "Exit",
    language = "Language",
    langAuto = "Auto (System)",
    langEnglish = "English",
    langChinese = "中文",
    currentVersionFmt = { version -> "Version: $version" },

    playerCenter = "Player Hub",
    newAccount = "New",
    createNewAccount = "New Account",
    winRecord = "Win Record",
    switchAccount = "Switch Account",
    winRateLabel = "Win%",
    winLossLabel = "W/L",
    totalGamesLabel = "Total",
    totalGames = "Games",
    wins = "Wins",
    losses = "Losses",
    renameTitle = "Rename",
    newNickname = "New name",
    nickname = "Name",
    noData = "No data yet",
    vsAiLabel = "vs AI",
    vsHumanLabel = "2 Players",

    remoteLobbyTitle = "Remote Play",
    creatingRoom = "Create Room",
    joiningRoom = "Join Room",
    waitingConnection = "Waiting",
    gameInProgress = "In Progress",
    connectionFailed = "Failed",
    cancelAction = "Cancel",
    backToMain = "Home",
    scanQr = "Scan",
    gallery = "Gallery",
    joinGame = "Join",
    inputInviteCode = "Enter Invite Code",
    inputInviteCodeHint = "Paste the invite code from your friend,\nor scan a QR code to join",
    inviteCodeLabel = "Invite Code",
    pasteInviteCode = "Paste invite code…",
    waitingHost = "Waiting for host…",
    preparing = "Preparing…",
    qrScanFailed = "QR code scan failed, please try again",
    qrNotFound = "No valid QR code found",
    qrImageLoadFailed = "Failed to load image, please try again",
    qrNotFoundDetail = "Please ensure the photo contains a complete and clear QR code",
    inviteCodeInvalidLan = "Invalid LAN invite code format",
    connectionTimeoutMsg = "Connection timed out. Please confirm the host has created a room and both devices are on the same network.",
    networkUnavailableMsg = "Cannot obtain local IP address. Please confirm Wi-Fi or hotspot is active.",
    relayUnavailableMsg = "Relay unavailable. Cannot join online room. Please use LAN mode instead.",
    versionMismatchMsg = "The other player may be using an incompatible version. Both should update to the latest.",

    opponent = "Opponent",
    me = "Me",
    requestDraw = "Draw?",
    resign = "Resign",
    connectionLost = "Disconnected. Reconnecting…",
    returnToLobby = "Lobby",
    confirmResignTitle = "Resign?",
    confirmResignText = "Resigning ends the game and clears the save.",
    confirmResign = "Confirm Resign",
    drawOfferedTitle = "Draw Offered",
    drawOfferedText = "Draw offer — accept?",
    acceptDraw = "Accept",
    rejectDraw = "Decline",
    drawSentWaiting = "Draw offer pending…",
    exitMatch = "Exit Match",
    exitMatchHint = "Review board then exit",
    rematchRequest = "Rematch",
    rematchRequestSent = "Waiting for opponent…",
    rematchOffered = { color -> "Rematch? Opponent plays $color" },
    rematchAccepted = "Opponent accepted",
    rematchRejected = "Opponent declined",
    rematchTimeout = "Request timed out",
    clickToRematch = "Tap to pick side",

    resumeBadge = "Resume",

    tutorialTitle = "Tutorial",

    tutorialIntroTitle = "About Gomoku",
    tutorialIntro1 = "Gomoku is a two-player strategy board game originating in ancient China. Simple to learn, yet full of strategic depth.",
    tutorialIntro2 = "The goal is to be the first to align five pieces in a row — horizontally, vertically, or diagonally. Easy to understand, hard to master.",
    tutorialRulesTitle = "Rules",
    tutorialRule1 = "Black moves first; players alternate placing pieces on intersections",
    tutorialRule2 = "Pieces cannot be moved or removed once placed",
    tutorialRule3 = "First to connect five in any direction (horizontal, vertical, diagonal) wins",
    tutorialRule4 = "Six or more in a row does not count as a win",
    tutorialRule5 = "A full board without a winner is a draw",
    tutorialModesTitle = "Game Modes",
    tutorialModeAiTitle = "vs Computer",
    tutorialModeAiDesc = "Play against an AI opponent. Choose from multiple difficulty levels: Easy, Medium, Hard, and Master. Great for practice.",
    tutorialModeHumanTitle = "2 Players",
    tutorialModeHumanDesc = "Two players take turns on the same device. Supports board flipping for face-to-face play. Perfect for playing with a friend.",
    tutorialFeaturesTitle = "Features",
    tutorialMagnifierTitle = "Magnifier",
    tutorialMagnifierDesc = "A magnifier appears while placing a piece, helping you position it precisely and avoid accidental taps.",
    tutorialAiHintTitle = "AI Hint",
    tutorialAiHintDesc = "Stuck? Tap the AI Hint button to receive the best move suggestion.",
    tutorialUndoFeatTitle = "Undo",
    tutorialUndoFeatDesc = "Tapped the wrong spot? Use Undo to take back your last move.",
    tutorialStatsFeatTitle = "Statistics",
    tutorialStatsFeatDesc = "Game results are recorded automatically. Check your win rate anytime.",
    tutorialTipsTitle = "Tips & Strategy",
    tutorialBeginnerLevel = "Beginner Tips",
    tutorialBeginnerTips = listOf(
        "Control the center: the center of the board has the highest strategic value",
        "Play offensively: don't just defend — actively create threats",
        "Watch for open threes: an open three (three in a row, both ends open) is key to winning"
    ),
    tutorialIntermLevel = "Intermediate Tips",
    tutorialIntermTips = listOf(
        "Double open-three: create two open-threes simultaneously — opponent can't block both",
        "Four + open-three: a four-in-a-row plus an open three is a forced win",
        "Counter-attack: while blocking the opponent, create opportunities for yourself",
        "Think three moves ahead: anticipate your opponent's responses and plan ahead"
    ),
    tutorialAdvancedLevel = "Advanced Tactics",
    tutorialAdvancedTips = listOf(
        "Opening theory: study classic openings such as Flower Moon and Ura Moon",
        "Forbidden moves: in formal play Black has restrictions on double-three, double-four, and overline",
        "Position evaluation: learn to assess who has the advantage in a given position",
        "Sacrifice for initiative: giving up local advantage can sometimes gain a global edge"
    ),
    tutorialFooter1 = "Practice makes perfect — keep playing to improve!",
    tutorialFooter2 = "Have fun!",

    remoteTagline = "Play with friends remotely",
    remoteSubtitle = "Connect via invite code or QR — end-to-end encrypted",
    remoteActiveGameTitle = "⚔️ Game in Progress",
    remoteResumeGame = "Resume Game",
    remoteEndGame = "End Game",
    remoteCreateHint = "Invite a friend — you play Black (first)",
    remoteCheckingRelays = "Checking relays…",
    remoteRelayDown = "Relay unavailable, tap to retry",
    remoteRelayDownNote = "Noted, won't auto-connect next time",
    remoteCreateOnline = "Create Room (Online)",
    remoteRelayStatus = { c, t -> "$c/$t relays connected" },
    remoteLanCreate = "LAN Room",
    remoteLanHint = "Same Wi-Fi or hotspot required",
    remoteJoinAction = "Join Game (paste or scan invite code)",
    remoteConnectedTitle = "Game in Progress",
    remoteGamePaused = "Game Paused",
    remoteYouBlack = "You play Black (first)",
    remoteYouWhite = "You play White (second)",
    remoteAutoReconnect = "Reconnecting to opponent…",
    remoteForfeit = "Forfeit",
    remoteLanRoomReady = "📶 LAN Room Ready",
    remoteShareInvite = "Share invite code with your friend",
    remoteLanInstructions = "Friend scans QR or pastes the code to start\nRequires same Wi-Fi or hotspot",
    remoteOnlineInstructions = "Friend scans QR or pastes the invite code\nto start the game automatically",
    remoteCopied = "Copied!",
    remoteCopyCode = "Copy Code",
    remoteSavedGallery = "Saved to Gallery 📷",
    remoteSaveFailed = "Failed — check storage permission",
    remoteSaveImage = "Save Image",
    remoteShareAction = "Share",
    remoteWaitingFriend = "Waiting for friend…",
    remoteProcessing = "Processing…",
    remoteRetry = "Retry",
    remoteRelayCount = { c, t -> "$c/$t Relays" },

    statusSelectFirst = "Choose who goes first",
    statusAiThinking = "AI is thinking...",
    statusBlackTurn = "Black's turn",
    statusWhiteTurn = "White's turn",
    statusAiTurnFmt = { color -> "$color's turn (AI)" },
    statusPlayerTurnFmt = { color -> "$color's turn (You)" },
    statusBlackWins = "Winner: Black",
    statusWhiteWins = "Winner: White",
    statusDraw = "Draw",
    statusGameOverBlackWins = "Game Over - Black Wins",
    statusGameOverWhiteWins = "Game Over - White Wins",
    statusGameOverDraw = "Game Over - Draw",
    statusGameOver = "Game Over",
    colorBlack = "Black",
    colorWhite = "White",
    playerHudYourTurn = "Your move",
    playerHudWaitOpponent = "Waiting for opponent",
    playerHudWin = "Victory! 🎉",
    playerHudLose = "Defeat",
    playerHudDraw = "Draw",
    playerHudReady = "Ready",
)

// ─── CompositionLocal ──────────────────────────────────────────────────────────

val LocalStrings = compositionLocalOf<AppStrings> { ZhStrings }
