use super::*;

pub(super) fn board_with_moves(moves: &[(usize, usize, Color)]) -> Board {
    let mut board = Board::new();
    for &(row, col, color) in moves {
        assert!(board.place(row, col, color));
    }
    board
}

const MASTER_ISSUE_TWO_MOVES: [(usize, usize, Color); 58] = [
    (7, 7, Color::Black),
    (7, 6, Color::White),
    (6, 7, Color::Black),
    (8, 7, Color::White),
    (6, 5, Color::Black),
    (6, 6, Color::White),
    (8, 6, Color::Black),
    (9, 8, Color::White),
    (10, 9, Color::Black),
    (6, 8, Color::White),
    (9, 7, Color::Black),
    (7, 5, Color::White),
    (5, 7, Color::Black),
    (4, 7, Color::White),
    (7, 8, Color::Black),
    (5, 6, Color::White),
    (4, 6, Color::Black),
    (2, 5, Color::White),
    (3, 6, Color::Black),
    (3, 5, Color::White),
    (4, 5, Color::Black),
    (2, 7, Color::White),
    (4, 4, Color::Black),
    (4, 3, Color::White),
    (3, 4, Color::Black),
    (3, 8, Color::White),
    (1, 6, Color::Black),
    (2, 9, Color::White),
    (1, 10, Color::Black),
    (2, 6, Color::White),
    (2, 8, Color::Black),
    (2, 4, Color::White),
    (2, 3, Color::Black),
    (1, 2, Color::White),
    (3, 9, Color::Black),
    (1, 8, Color::White),
    (3, 10, Color::Black),
    (4, 10, Color::White),
    (5, 9, Color::Black),
    (3, 7, Color::White),
    (1, 5, Color::Black),
    (1, 7, Color::White),
    (0, 7, Color::Black),
    (4, 9, Color::White),
    (5, 10, Color::Black),
    (4, 8, Color::White),
    (4, 11, Color::Black),
    (5, 8, Color::White),
    (3, 12, Color::Black),
    (6, 9, Color::White),
    (2, 11, Color::Black),
    (7, 10, Color::White),
    (8, 11, Color::Black),
    (0, 9, Color::White),
    (3, 11, Color::Black),
    (3, 13, Color::White),
    (5, 11, Color::Black),
    (6, 11, Color::White),
];

pub(super) fn master_issue_two_prefix_board(ply_count: usize) -> Board {
    board_with_moves(&MASTER_ISSUE_TWO_MOVES[..ply_count])
}

pub(super) fn transcript_board_21() -> Board {
    board_with_moves(&[
        (7, 7, Color::Black),
        (7, 6, Color::White),
        (6, 7, Color::Black),
        (8, 7, Color::White),
        (6, 5, Color::Black),
        (9, 8, Color::White),
        (6, 6, Color::Black),
        (10, 9, Color::White),
        (11, 10, Color::Black),
        (6, 4, Color::White),
        (6, 8, Color::Black),
        (6, 9, Color::White),
        (8, 9, Color::Black),
        (7, 8, Color::White),
        (9, 6, Color::Black),
        (5, 10, Color::White),
        (4, 11, Color::Black),
        (10, 8, Color::White),
        (10, 7, Color::Black),
        (8, 8, Color::White),
        (11, 8, Color::Black),
    ])
}

pub(super) fn transcript_board_24() -> Board {
    board_with_moves(&[
        (7, 7, Color::Black),
        (7, 6, Color::White),
        (6, 7, Color::Black),
        (8, 7, Color::White),
        (6, 5, Color::Black),
        (9, 8, Color::White),
        (6, 6, Color::Black),
        (10, 9, Color::White),
        (11, 10, Color::Black),
        (6, 4, Color::White),
        (6, 8, Color::Black),
        (6, 9, Color::White),
        (8, 9, Color::Black),
        (7, 8, Color::White),
        (9, 6, Color::Black),
        (5, 10, Color::White),
        (4, 11, Color::Black),
        (10, 8, Color::White),
        (10, 7, Color::Black),
        (8, 8, Color::White),
        (11, 8, Color::Black),
        (12, 9, Color::White),
        (8, 5, Color::Black),
        (7, 4, Color::White),
    ])
}

pub(super) fn transcript_board_26() -> Board {
    board_with_moves(&[
        (7, 7, Color::Black),
        (7, 6, Color::White),
        (6, 7, Color::Black),
        (8, 7, Color::White),
        (6, 5, Color::Black),
        (9, 8, Color::White),
        (6, 6, Color::Black),
        (10, 9, Color::White),
        (11, 10, Color::Black),
        (6, 4, Color::White),
        (6, 8, Color::Black),
        (6, 9, Color::White),
        (8, 9, Color::Black),
        (7, 8, Color::White),
        (9, 6, Color::Black),
        (5, 10, Color::White),
        (4, 11, Color::Black),
        (10, 8, Color::White),
        (10, 7, Color::Black),
        (8, 8, Color::White),
        (11, 8, Color::Black),
        (12, 9, Color::White),
        (8, 5, Color::Black),
        (7, 4, Color::White),
        (9, 5, Color::Black),
        (7, 5, Color::White),
    ])
}

pub(super) fn transcript_board_27_new_issue() -> Board {
    board_with_moves(&[
        (7, 7, Color::Black),
        (7, 6, Color::White),
        (6, 7, Color::Black),
        (8, 7, Color::White),
        (6, 5, Color::Black),
        (9, 8, Color::White),
        (6, 6, Color::Black),
        (10, 9, Color::White),
        (11, 10, Color::Black),
        (6, 4, Color::White),
        (6, 8, Color::Black),
        (6, 9, Color::White),
        (8, 9, Color::Black),
        (7, 8, Color::White),
        (9, 6, Color::Black),
        (5, 10, Color::White),
        (4, 11, Color::Black),
        (10, 8, Color::White),
        (10, 7, Color::Black),
        (8, 8, Color::White),
        (11, 8, Color::Black),
        (8, 5, Color::White),
        (12, 9, Color::Black),
        (13, 10, Color::White),
        (8, 4, Color::Black),
        (9, 7, Color::White),
        (7, 5, Color::Black),
    ])
}

pub(super) fn master_issue_before_black_39_board() -> Board {
    board_with_moves(&[
        (7, 7, Color::Black),
        (8, 7, Color::White),
        (7, 6, Color::Black),
        (7, 8, Color::White),
        (9, 6, Color::Black),
        (8, 6, Color::White),
        (8, 5, Color::Black),
        (7, 4, Color::White),
        (9, 4, Color::Black),
        (6, 7, Color::White),
        (10, 3, Color::Black),
        (11, 2, Color::White),
        (10, 5, Color::Black),
        (9, 5, Color::White),
        (8, 3, Color::Black),
        (11, 6, Color::White),
        (7, 2, Color::Black),
        (6, 1, Color::White),
        (11, 4, Color::Black),
        (10, 4, Color::White),
        (12, 3, Color::Black),
        (13, 2, Color::White),
        (11, 3, Color::Black),
        (9, 3, Color::White),
        (13, 3, Color::Black),
        (14, 3, Color::White),
        (12, 2, Color::Black),
        (12, 5, Color::White),
        (13, 4, Color::Black),
        (12, 6, Color::White),
        (11, 5, Color::Black),
        (12, 7, Color::White),
        (12, 4, Color::Black),
        (9, 7, Color::White),
        (10, 6, Color::Black),
        (14, 2, Color::White),
        (12, 1, Color::Black),
        (12, 0, Color::White),
    ])
}

pub(super) fn master_issue_after_black_39_board() -> Board {
    board_with_moves(&[
        (7, 7, Color::Black),
        (8, 7, Color::White),
        (7, 6, Color::Black),
        (7, 8, Color::White),
        (9, 6, Color::Black),
        (8, 6, Color::White),
        (8, 5, Color::Black),
        (7, 4, Color::White),
        (9, 4, Color::Black),
        (6, 7, Color::White),
        (10, 3, Color::Black),
        (11, 2, Color::White),
        (10, 5, Color::Black),
        (9, 5, Color::White),
        (8, 3, Color::Black),
        (11, 6, Color::White),
        (7, 2, Color::Black),
        (6, 1, Color::White),
        (11, 4, Color::Black),
        (10, 4, Color::White),
        (12, 3, Color::Black),
        (13, 2, Color::White),
        (11, 3, Color::Black),
        (9, 3, Color::White),
        (13, 3, Color::Black),
        (14, 3, Color::White),
        (12, 2, Color::Black),
        (12, 5, Color::White),
        (13, 4, Color::Black),
        (12, 6, Color::White),
        (11, 5, Color::Black),
        (12, 7, Color::White),
        (12, 4, Color::Black),
        (9, 7, Color::White),
        (10, 6, Color::Black),
        (14, 2, Color::White),
        (12, 1, Color::Black),
        (12, 0, Color::White),
        (12, 8, Color::Black),
    ])
}
